version: '2'

services:
  todo:
    restart: always
    build: ./TodoProject
    expose:
     - "8000"
    links:
      - pg:pg
      - redis:redis

  pg:
    restart: always
    image: postgres:10
    expose:
      - "5432"
    env_file:
      - .env
    volumes_from:
      - data-container

  nginx:
    restart: always
    image: harshvardhan03/todo-nginx:v1
    ports:
      - "80:80"
    links:
      - todo:todo

  redis:
    restart: always
    image: redis:5
    ports:
      - "6379:6379"
  
  data-container:
    restart: always
    image: alpine
    volumes:
      - /var/lib/postgresql/data/
    command: "true" 


